version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_database
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  worker:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: worker
    restart: on-failure
    depends_on:
      - db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      RAW_INPUT_PATH: /app/worker
      RAW_OUTPUT_PATH: /app/worker
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - db
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow_webserver
    restart: always
    depends_on:
      - db
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@db:5432/postgres
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - AIRFLOW__WEBSERVER__SECRET_KEY=AlanPoliUSP2026
      - PYTHONPATH=/opt/airflow:/opt/airflow/worker
      - RAW_INPUT_PATH=/opt/airflow/worker
      - RAW_OUTPUT_PATH=/opt/airflow/worker
      - AIRFLOW__CORE__PARALLELISM=1
      - AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG=1
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./worker:/opt/airflow/worker
      - ./data_quality:/opt/airflow/data_quality
      - ./gx:/opt/airflow/gx
    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - db
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@db:5432/postgres
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - AIRFLOW__WEBSERVER__SECRET_KEY=AlanPoliUSP2026
      - PYTHONPATH=/opt/airflow:/opt/airflow/worker
      - RAW_INPUT_PATH=/opt/airflow/worker
      - RAW_OUTPUT_PATH=/opt/airflow/worker
      - AIRFLOW__SCHEDULER__SCHEDULER_ZOMBIE_TASK_THRESHOLD=1200
    volumes:
      - ./dags:/opt/airflow/dags
      - ./worker:/opt/airflow/worker
      - ./data_quality:/opt/airflow/data_quality
      - ./gx:/opt/airflow/gx
    command: scheduler

volumes:
  postgres_data:
  grafana_data: